services:
  - type: web
    name: wgarage-app
    env: node
    plan: free
    buildCommand: cd server && npm install && npm run init-db
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
