services:
  - type: web
    name: wgarage-app
    env: node
    plan: free
    buildCommand: npm install && node init-db.js
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: PORT
        value: 10000
